// Package upload_file implements the upload_file MCP tool: uploads a file to an
// edge site and returns an artifact URI usable as the value of any FILE-type
// connection or capability parameter (JDBC drivers, TLS certs, private keys,
// keytabs, etc.).
//
// Policy: this tool deliberately does NOT fetch file content from an arbitrary URL
// (e.g. Maven Central). For JDBC drivers specifically, Collibra only supports/
// verifies drivers distributed through Collibra Marketplace, and Marketplace
// downloads require an authenticated account — there is no public, unauthenticated
// download endpoint to automate. get_data_source_setup_guide's marketplaceUrl field
// points to the correct listing; the user must download the driver from there
// themselves and hand the bytes to this tool. Do not substitute an unverified source
// (Maven Central, GitHub releases, etc.) for a driver jar just because it's more
// convenient to automate — ask the user for the file instead.
//
// Large files and the two Input variants (documented gap for chip-service):
//
// contentBase64 has a hard ceiling that isn't really about encoding or transport: any
// value passed as a tool-call argument has to be generated by the calling model
// itself, token by token, as part of its own output. A 96MB JDBC driver jar becomes
// ~130MB of base64 text the model would have to produce — that holds regardless of
// encoding, MCP transport, or how this tool is implemented.
//
// filePath (reading the file directly off local disk, server-side, bypassing the
// model entirely) fixes this — but only makes sense when chip is running as a local
// process with access to the caller's own filesystem. That's true for the standalone
// `chip` binary (a real, documented distribution channel — see the repo README —
// where a user runs chip locally against their own tenant), but not for chip-service,
// the product's remote, multi-tenant deployment: there, "local disk" means the server
// container's disk, not any user's machine, and a filePath input would be a genuine
// arbitrary-file-read vulnerability if ever reachable.
//
// Both binaries call the same tools.RegisterAll, so filePath support is exposed as a
// second, separate Input type (InputWithFilePath) registered under an unchanged tool
// name ("upload_file") only when chip.ServerToolConfig.AllowLocalFileUpload is true.
// This is gated at registration time, not inside the handler on every call: only
// cmd/chip's own startup wiring ever sets AllowLocalFileUpload, so chip-service's
// binary has no code path that could turn it on, even by mistake. If chip-service
// ever needs equivalent large-file support, it needs its own solution appropriate to
// a remote, multi-tenant server (e.g. a presigned upload step, or client-side file
// attachment support in whatever chat surface embeds it) — not this field.
//
// For chip-service today, the only large-file workaround is manual: guide the user
// to create the whole connection through the Collibra Edge UI (Settings > Edge >
// site > Connections > New), supplying the exact field values yourself (driver
// class, connection string — from get_data_source_setup_guide) so they only have to
// pick the file and click through, since there is no standalone "upload just the
// driver, get a reference back" screen or API — confirmed by checking the newer
// catalog-backed driver API (POST /rest/edge/v1/drivers/jars), which has no UI in
// front of it at all, and the frontend's only file-upload path is the legacy one
// embedded inside the connection-creation form's own FILE-type field. Once the user
// confirms the connection is saved, use edge_find_connections (by name) to pick up its
// id and proceed with edge_create_capability/register_database/
// configure_database_schemas/start_ingestion against it — skip edge_create_connection
// entirely for that connection, since it already exists.
package upload_file

import (
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"os"

	"github.com/collibra/chip/pkg/chip"
	"github.com/collibra/chip/pkg/clients"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Input is used when local file uploads are not enabled (the default, and always the
// case for chip-service) — content must be supplied inline as base64.
type Input struct {
	Filename      string `json:"filename" jsonschema:"The filename to upload as (e.g. 'client-cert.pem', 'snowflake-jdbc-3.23.2.jar'). Determines the file extension DGC uses to infer the artifact type."`
	ContentBase64 string `json:"contentBase64" jsonschema:"The file's content, base64-encoded. For a JDBC driver, this must come from a file the user downloaded from Collibra Marketplace (see get_data_source_setup_guide's marketplaceUrl) — never fetch a driver from an arbitrary URL like Maven Central; ask the user for the file instead. Large files (tens of MB, as most JDBC drivers are) will not fit here — if the content would be too large to include, ask the user to create the connection manually via the Collibra Edge UI instead and pick it up afterward with edge_find_connections."`
}

// InputWithFilePath is used when AllowLocalFileUpload is true (only ever set by the
// standalone chip binary, never chip-service) — adds filePath as an alternative to
// contentBase64 for large files.
type InputWithFilePath struct {
	Filename      string `json:"filename" jsonschema:"The filename to upload as (e.g. 'client-cert.pem', 'snowflake-jdbc-3.23.2.jar'). Determines the file extension DGC uses to infer the artifact type."`
	ContentBase64 string `json:"contentBase64,omitempty" jsonschema:"The file's content, base64-encoded. Exactly one of contentBase64 or filePath must be provided. Prefer filePath for large files (tens of MB, as most JDBC drivers are) — contentBase64 will not fit them in a tool call."`
	FilePath      string `json:"filePath,omitempty" jsonschema:"Absolute path to a local file to read and upload directly from this machine's disk, without passing its content through the conversation. Available because this chip instance is running locally with access to your own filesystem. Exactly one of contentBase64 or filePath must be provided."`
}

type Output struct {
	URI     string `json:"uri,omitempty" jsonschema:"The uploaded artifact URI (e.g. 'jar://<uuid>/<filename>'). Use this as the value of a FILE-type connection or capability parameter."`
	Success bool   `json:"success" jsonschema:"Whether the file was uploaded successfully."`
	Error   string `json:"error,omitempty" jsonschema:"Error message if the upload failed."`
}

// NewTool registers upload_file without filePath support (contentBase64 only). Used
// whenever AllowLocalFileUpload is false — always true for chip-service.
func NewTool(collibraClient *http.Client) *chip.Tool[Input, Output] {
	return &chip.Tool[Input, Output]{
		Name:        "upload_file",
		Title:       "Upload File to Edge Site",
		Description: "Uploads a file (JDBC driver, TLS certificate, private key, keytab, etc.) to an edge site and returns an artifact URI usable as the value of any FILE-type connection or capability parameter. Takes file content directly (base64) — does not fetch from a URL. Only suitable for small files (contentBase64 has to fit in a tool call); for a large file (e.g. most JDBC drivers), guide the user to create the connection manually via the Collibra Edge UI and pick it up with edge_find_connections. For JDBC drivers, only use content downloaded from Collibra Marketplace (verified/supported), never an arbitrary host; get the Marketplace listing URL from get_data_source_setup_guide.",
		Handler: func(ctx context.Context, input Input) (Output, error) {
			return upload(ctx, collibraClient, input.Filename, input.ContentBase64, "")
		},
		Permissions: []string{"dgc.edge-integration-capability-manage"},
		Annotations: &mcp.ToolAnnotations{DestructiveHint: chip.Ptr(true)},
	}
}

// NewToolWithFilePath registers upload_file with filePath support added. Only called
// when chip.ServerToolConfig.AllowLocalFileUpload is true — see package doc comment
// for why this must never happen in chip-service.
func NewToolWithFilePath(collibraClient *http.Client) *chip.Tool[InputWithFilePath, Output] {
	return &chip.Tool[InputWithFilePath, Output]{
		Name:        "upload_file",
		Title:       "Upload File to Edge Site",
		Description: "Uploads a file (JDBC driver, TLS certificate, private key, keytab, etc.) to an edge site and returns an artifact URI usable as the value of any FILE-type connection or capability parameter. Does not fetch from a URL. Prefer filePath for large files (e.g. most JDBC drivers) — it reads the file directly from this machine's disk, avoiding the base64-in-tool-call size limit. For JDBC drivers, only use a file downloaded from Collibra Marketplace (verified/supported), never an arbitrary host; get the Marketplace listing URL from get_data_source_setup_guide.",
		Handler: func(ctx context.Context, input InputWithFilePath) (Output, error) {
			return upload(ctx, collibraClient, input.Filename, input.ContentBase64, input.FilePath)
		},
		Permissions: []string{"dgc.edge-integration-capability-manage"},
		Annotations: &mcp.ToolAnnotations{DestructiveHint: chip.Ptr(true)},
	}
}

func upload(ctx context.Context, collibraClient *http.Client, filename, contentBase64, filePath string) (Output, error) {
	if filename == "" {
		return Output{}, fmt.Errorf("filename is required")
	}

	hasContent := contentBase64 != ""
	hasFilePath := filePath != ""
	if hasContent == hasFilePath {
		return Output{}, fmt.Errorf("exactly one of contentBase64 or filePath must be provided")
	}

	var content []byte
	if hasFilePath {
		data, err := os.ReadFile(filePath)
		if err != nil {
			return Output{Success: false, Error: fmt.Sprintf("failed to read file %q: %s", filePath, err.Error())}, nil
		}
		content = data
	} else {
		decoded, err := base64.StdEncoding.DecodeString(contentBase64)
		if err != nil {
			return Output{}, fmt.Errorf("decoding contentBase64: %w", err)
		}
		content = decoded
	}

	uri, err := clients.UploadFile(ctx, collibraClient, filename, content)
	if err != nil {
		return Output{Success: false, Error: fmt.Sprintf("failed to upload file: %s", err.Error())}, nil
	}

	return Output{URI: uri, Success: true}, nil
}
