package get_business_term_test

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/collibra/chip/pkg/clients"
	"github.com/collibra/chip/pkg/tools/get_business_term"
	"github.com/collibra/chip/pkg/tools/testutil"
)

// newRelation is a test helper that builds a GetBusinessTermRelation.
func newRelation(id, srcID, srcName, srcType, tgtID, tgtName, tgtType, relID, relName string) clients.GetBusinessTermRelation {
	return clients.GetBusinessTermRelation{
		ID:     id,
		Source: clients.GetBusinessTermRelationAsset{ID: srcID, Name: srcName, Type: clients.GetBusinessTermAssetType{Name: srcType}},
		Target: clients.GetBusinessTermRelationAsset{ID: tgtID, Name: tgtName, Type: clients.GetBusinessTermAssetType{Name: tgtType}},
		Type:   clients.GetBusinessTermRelationType{ID: relID, Name: relName},
	}
}

// setupFullLineageServer creates a test server with a complete lineage chain:
// Business Term (bt-001) → Data Attribute (da-001) → Table (tbl-001) → Column (col-001)
func setupFullLineageServer() *httptest.Server {
	mux := http.NewServeMux()

	mux.Handle("GET /rest/2.0/attributes", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAttributesResponse) {
			return http.StatusOK, clients.GetBusinessTermAttributesResponse{
				Total: 3,
				Results: []clients.GetBusinessTermAttributeResponse{
					{
						ID:    "attr-001",
						Type:  clients.GetBusinessTermAttributeType{ID: "atype-1", Name: "Definition"},
						Value: "Total revenue generated by a customer",
					},
					{
						ID:    "attr-002",
						Type:  clients.GetBusinessTermAttributeType{ID: "atype-2", Name: "Note"},
						Value: "Calculated quarterly",
					},
					{
						ID:    "attr-003",
						Type:  clients.GetBusinessTermAttributeType{ID: "atype-3", Name: "Example"},
						Value: "$1,234.56",
					},
				},
			}
		},
	))

	mux.Handle("GET /rest/2.0/assets/{id}", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAssetResponse) {
			id := r.PathValue("id")
			if id == "bt-001" {
				return http.StatusOK, clients.GetBusinessTermAssetResponse{
					ID:          "bt-001",
					Name:        "Customer Revenue",
					DisplayName: "Customer Revenue",
					Type:        clients.GetBusinessTermAssetType{ID: "type-bt", Name: "Business Term"},
					Domain:      clients.GetBusinessTermDomain{ID: "dom-001", Name: "Finance"},
					Status:      clients.GetBusinessTermStatus{ID: "st-001", Name: "Approved"},
				}
			}
			return http.StatusNotFound, clients.GetBusinessTermAssetResponse{}
		},
	))

	mux.Handle("GET /rest/2.0/relations", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermRelationsResponse) {
			sourceID := r.URL.Query().Get("sourceId")
			switch sourceID {
			case "bt-001":
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 1,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-1", "bt-001", "Customer Revenue", "Business Term",
							"da-001", "Revenue Attribute", "Data Attribute", "rtype-1", "describes"),
					},
				}
			case "da-001":
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 1,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-2", "da-001", "Revenue Attribute", "Data Attribute",
							"tbl-001", "sales_transactions", "Table", "rtype-2", "isPartOf"),
					},
				}
			case "tbl-001":
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 1,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-3", "tbl-001", "sales_transactions", "Table",
							"col-001", "revenue_amount", "Column", "rtype-3", "contains"),
					},
				}
			default:
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{Total: 0, Results: []clients.GetBusinessTermRelation{}}
			}
		},
	))

	return httptest.NewServer(mux)
}

func TestGetBusinessTerm_FullLineage(t *testing.T) {
	server := setupFullLineageServer()
	defer server.Close()

	client := testutil.NewClient(server)
	output, err := get_business_term.NewTool(client).Handler(t.Context(), get_business_term.Input{
		AssetID: "bt-001",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Verify asset details.
	if output.ID != "bt-001" {
		t.Errorf("ID: got %q, want %q", output.ID, "bt-001")
	}
	if output.Name != "Customer Revenue" {
		t.Errorf("Name: got %q, want %q", output.Name, "Customer Revenue")
	}
	if output.AssetType != "Business Term" {
		t.Errorf("AssetType: got %q, want %q", output.AssetType, "Business Term")
	}
	if output.DomainID != "dom-001" {
		t.Errorf("DomainID: got %q, want %q", output.DomainID, "dom-001")
	}
	if output.DomainName != "Finance" {
		t.Errorf("DomainName: got %q, want %q", output.DomainName, "Finance")
	}
	if output.StatusName != "Approved" {
		t.Errorf("StatusName: got %q, want %q", output.StatusName, "Approved")
	}

	// Verify attributes.
	if len(output.Attributes) != 3 {
		t.Fatalf("Attributes: got %d, want 3", len(output.Attributes))
	}
	wantAttrs := []struct{ name, value string }{
		{"Definition", "Total revenue generated by a customer"},
		{"Note", "Calculated quarterly"},
		{"Example", "$1,234.56"},
	}
	for i, want := range wantAttrs {
		if output.Attributes[i].Name != want.name {
			t.Errorf("Attributes[%d].Name: got %q, want %q", i, output.Attributes[i].Name, want.name)
		}
		if output.Attributes[i].Value != want.value {
			t.Errorf("Attributes[%d].Value: got %q, want %q", i, output.Attributes[i].Value, want.value)
		}
	}

	// Verify lineage: BT → DA → Table → Column.
	if len(output.Lineage) != 1 {
		t.Fatalf("Lineage: got %d data attributes, want 1", len(output.Lineage))
	}

	da := output.Lineage[0]
	if da.ID != "da-001" {
		t.Errorf("DA ID: got %q, want %q", da.ID, "da-001")
	}
	if da.Name != "Revenue Attribute" {
		t.Errorf("DA Name: got %q, want %q", da.Name, "Revenue Attribute")
	}
	if da.RelationType != "describes" {
		t.Errorf("DA RelationType: got %q, want %q", da.RelationType, "describes")
	}

	if len(da.Tables) != 1 {
		t.Fatalf("Tables: got %d, want 1", len(da.Tables))
	}
	table := da.Tables[0]
	if table.ID != "tbl-001" {
		t.Errorf("Table ID: got %q, want %q", table.ID, "tbl-001")
	}
	if table.Name != "sales_transactions" {
		t.Errorf("Table Name: got %q, want %q", table.Name, "sales_transactions")
	}
	if table.RelationType != "isPartOf" {
		t.Errorf("Table RelationType: got %q, want %q", table.RelationType, "isPartOf")
	}

	if len(table.Columns) != 1 {
		t.Fatalf("Columns: got %d, want 1", len(table.Columns))
	}
	col := table.Columns[0]
	if col.ID != "col-001" {
		t.Errorf("Column ID: got %q, want %q", col.ID, "col-001")
	}
	if col.Name != "revenue_amount" {
		t.Errorf("Column Name: got %q, want %q", col.Name, "revenue_amount")
	}
	if col.RelationType != "contains" {
		t.Errorf("Column RelationType: got %q, want %q", col.RelationType, "contains")
	}
}

func TestGetBusinessTerm_NotFound(t *testing.T) {
	server := setupFullLineageServer()
	defer server.Close()

	client := testutil.NewClient(server)
	_, err := get_business_term.NewTool(client).Handler(t.Context(), get_business_term.Input{
		AssetID: "nonexistent-id",
	})
	if err == nil {
		t.Fatal("expected error for nonexistent asset, got nil")
	}
}

func TestGetBusinessTerm_EmptyAssetID(t *testing.T) {
	server := setupFullLineageServer()
	defer server.Close()

	client := testutil.NewClient(server)
	_, err := get_business_term.NewTool(client).Handler(t.Context(), get_business_term.Input{
		AssetID: "",
	})
	if err == nil {
		t.Fatal("expected error for empty asset_id, got nil")
	}
}

func TestGetBusinessTerm_NoAttributesNoLineage(t *testing.T) {
	mux := http.NewServeMux()

	mux.Handle("GET /rest/2.0/attributes", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAttributesResponse) {
			return http.StatusOK, clients.GetBusinessTermAttributesResponse{Total: 0, Results: []clients.GetBusinessTermAttributeResponse{}}
		},
	))

	mux.Handle("GET /rest/2.0/assets/{id}", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAssetResponse) {
			return http.StatusOK, clients.GetBusinessTermAssetResponse{
				ID:     "bt-empty",
				Name:   "Empty Term",
				Type:   clients.GetBusinessTermAssetType{ID: "type-bt", Name: "Business Term"},
				Domain: clients.GetBusinessTermDomain{ID: "dom-001", Name: "General"},
				Status: clients.GetBusinessTermStatus{ID: "st-001", Name: "Draft"},
			}
		},
	))

	mux.Handle("GET /rest/2.0/relations", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermRelationsResponse) {
			return http.StatusOK, clients.GetBusinessTermRelationsResponse{Total: 0, Results: []clients.GetBusinessTermRelation{}}
		},
	))

	server := httptest.NewServer(mux)
	defer server.Close()

	client := testutil.NewClient(server)
	output, err := get_business_term.NewTool(client).Handler(t.Context(), get_business_term.Input{
		AssetID: "bt-empty",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if output.Name != "Empty Term" {
		t.Errorf("Name: got %q, want %q", output.Name, "Empty Term")
	}
	if len(output.Attributes) != 0 {
		t.Errorf("Attributes: got %d, want 0", len(output.Attributes))
	}
	if len(output.Lineage) != 0 {
		t.Errorf("Lineage: got %d, want 0", len(output.Lineage))
	}
}

func TestGetBusinessTerm_FiltersNonPhysicalData(t *testing.T) {
	mux := http.NewServeMux()

	mux.Handle("GET /rest/2.0/attributes", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAttributesResponse) {
			return http.StatusOK, clients.GetBusinessTermAttributesResponse{Total: 0, Results: []clients.GetBusinessTermAttributeResponse{}}
		},
	))

	mux.Handle("GET /rest/2.0/assets/{id}", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAssetResponse) {
			return http.StatusOK, clients.GetBusinessTermAssetResponse{
				ID:     "bt-filter",
				Name:   "Filtered Term",
				Type:   clients.GetBusinessTermAssetType{ID: "type-bt", Name: "Business Term"},
				Domain: clients.GetBusinessTermDomain{ID: "dom-001", Name: "Sales"},
				Status: clients.GetBusinessTermStatus{ID: "st-001", Name: "Approved"},
			}
		},
	))

	mux.Handle("GET /rest/2.0/relations", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermRelationsResponse) {
			sourceID := r.URL.Query().Get("sourceId")
			switch sourceID {
			case "bt-filter":
				// Return a mix of physical and non-physical relation targets.
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 3,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-a", "bt-filter", "Filtered Term", "Business Term",
							"da-100", "Good DA", "Data Attribute", "rtype-1", "describes"),
						newRelation("rel-b", "bt-filter", "Filtered Term", "Business Term",
							"rpt-001", "Some Report", "Report", "rtype-x", "generates"),
						newRelation("rel-c", "bt-filter", "Filtered Term", "Business Term",
							"pol-001", "Some Policy", "Data Policy", "rtype-y", "governedBy"),
					},
				}
			case "da-100":
				// Data Attribute has a Table and a non-physical target.
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 2,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-d", "da-100", "Good DA", "Data Attribute",
							"tbl-100", "orders", "Table", "rtype-2", "isPartOf"),
						newRelation("rel-e", "da-100", "Good DA", "Data Attribute",
							"dash-001", "Dashboard", "Dashboard", "rtype-z", "visualizedIn"),
					},
				}
			case "tbl-100":
				// Table has a Column and a non-physical target.
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 2,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-f", "tbl-100", "orders", "Table",
							"col-100", "order_id", "Column", "rtype-3", "contains"),
						newRelation("rel-g", "tbl-100", "orders", "Table",
							"idx-001", "pk_orders", "Index", "rtype-w", "indexes"),
					},
				}
			default:
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{Total: 0, Results: []clients.GetBusinessTermRelation{}}
			}
		},
	))

	server := httptest.NewServer(mux)
	defer server.Close()

	client := testutil.NewClient(server)
	output, err := get_business_term.NewTool(client).Handler(t.Context(), get_business_term.Input{
		AssetID: "bt-filter",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Only the Data Attribute should appear in lineage (Report and Data Policy filtered out).
	if len(output.Lineage) != 1 {
		t.Fatalf("Lineage: got %d, want 1 (only Data Attribute)", len(output.Lineage))
	}
	da := output.Lineage[0]
	if da.ID != "da-100" {
		t.Errorf("DA ID: got %q, want %q", da.ID, "da-100")
	}

	// Only the Table should appear (Dashboard filtered out).
	if len(da.Tables) != 1 {
		t.Fatalf("Tables: got %d, want 1 (only Table)", len(da.Tables))
	}
	if da.Tables[0].ID != "tbl-100" {
		t.Errorf("Table ID: got %q, want %q", da.Tables[0].ID, "tbl-100")
	}

	// Only the Column should appear (Index filtered out).
	if len(da.Tables[0].Columns) != 1 {
		t.Fatalf("Columns: got %d, want 1 (only Column)", len(da.Tables[0].Columns))
	}
	if da.Tables[0].Columns[0].ID != "col-100" {
		t.Errorf("Column ID: got %q, want %q", da.Tables[0].Columns[0].ID, "col-100")
	}
}

func TestGetBusinessTerm_MultipleDataAttributes(t *testing.T) {
	mux := http.NewServeMux()

	mux.Handle("GET /rest/2.0/attributes", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAttributesResponse) {
			return http.StatusOK, clients.GetBusinessTermAttributesResponse{
				Total: 1,
				Results: []clients.GetBusinessTermAttributeResponse{
					{
						ID:    "attr-010",
						Type:  clients.GetBusinessTermAttributeType{ID: "atype-1", Name: "Definition"},
						Value: "A customer identifier",
					},
				},
			}
		},
	))

	mux.Handle("GET /rest/2.0/assets/{id}", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAssetResponse) {
			return http.StatusOK, clients.GetBusinessTermAssetResponse{
				ID:     "bt-multi",
				Name:   "Customer ID",
				Type:   clients.GetBusinessTermAssetType{ID: "type-bt", Name: "Business Term"},
				Domain: clients.GetBusinessTermDomain{ID: "dom-002", Name: "CRM"},
				Status: clients.GetBusinessTermStatus{ID: "st-002", Name: "Candidate"},
			}
		},
	))

	mux.Handle("GET /rest/2.0/relations", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermRelationsResponse) {
			sourceID := r.URL.Query().Get("sourceId")
			switch sourceID {
			case "bt-multi":
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 2,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-m1", "bt-multi", "Customer ID", "Business Term",
							"da-m1", "CRM Customer Attr", "Data Attribute", "rt-1", "maps"),
						newRelation("rel-m2", "bt-multi", "Customer ID", "Business Term",
							"da-m2", "Billing Customer Attr", "Data Attribute", "rt-1", "maps"),
					},
				}
			case "da-m1":
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 1,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-m3", "da-m1", "CRM Customer Attr", "Data Attribute",
							"tbl-m1", "crm_customers", "Table", "rt-2", "isPartOf"),
					},
				}
			case "da-m2":
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 1,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-m4", "da-m2", "Billing Customer Attr", "Data Attribute",
							"tbl-m2", "billing_accounts", "Table", "rt-2", "isPartOf"),
					},
				}
			case "tbl-m1":
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 2,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-m5", "tbl-m1", "crm_customers", "Table",
							"col-m1", "customer_id", "Column", "rt-3", "contains"),
						newRelation("rel-m6", "tbl-m1", "crm_customers", "Table",
							"col-m2", "customer_name", "Column", "rt-3", "contains"),
					},
				}
			case "tbl-m2":
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{
					Total: 1,
					Results: []clients.GetBusinessTermRelation{
						newRelation("rel-m7", "tbl-m2", "billing_accounts", "Table",
							"col-m3", "account_id", "Column", "rt-3", "contains"),
					},
				}
			default:
				return http.StatusOK, clients.GetBusinessTermRelationsResponse{Total: 0, Results: []clients.GetBusinessTermRelation{}}
			}
		},
	))

	server := httptest.NewServer(mux)
	defer server.Close()

	client := testutil.NewClient(server)
	output, err := get_business_term.NewTool(client).Handler(t.Context(), get_business_term.Input{
		AssetID: "bt-multi",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if output.Name != "Customer ID" {
		t.Errorf("Name: got %q, want %q", output.Name, "Customer ID")
	}
	if output.DomainName != "CRM" {
		t.Errorf("DomainName: got %q, want %q", output.DomainName, "CRM")
	}

	// Two Data Attributes in lineage.
	if len(output.Lineage) != 2 {
		t.Fatalf("Lineage: got %d data attributes, want 2", len(output.Lineage))
	}

	// First DA: CRM Customer Attr → crm_customers → [customer_id, customer_name]
	da1 := output.Lineage[0]
	if da1.Name != "CRM Customer Attr" {
		t.Errorf("DA1 Name: got %q, want %q", da1.Name, "CRM Customer Attr")
	}
	if len(da1.Tables) != 1 {
		t.Fatalf("DA1 Tables: got %d, want 1", len(da1.Tables))
	}
	if len(da1.Tables[0].Columns) != 2 {
		t.Fatalf("DA1 Table Columns: got %d, want 2", len(da1.Tables[0].Columns))
	}

	// Second DA: Billing Customer Attr → billing_accounts → [account_id]
	da2 := output.Lineage[1]
	if da2.Name != "Billing Customer Attr" {
		t.Errorf("DA2 Name: got %q, want %q", da2.Name, "Billing Customer Attr")
	}
	if len(da2.Tables) != 1 {
		t.Fatalf("DA2 Tables: got %d, want 1", len(da2.Tables))
	}
	if len(da2.Tables[0].Columns) != 1 {
		t.Fatalf("DA2 Table Columns: got %d, want 1", len(da2.Tables[0].Columns))
	}
	if da2.Tables[0].Columns[0].Name != "account_id" {
		t.Errorf("DA2 Column Name: got %q, want %q", da2.Tables[0].Columns[0].Name, "account_id")
	}
}

func TestGetBusinessTerm_ServerError(t *testing.T) {
	mux := http.NewServeMux()

	mux.Handle("GET /rest/2.0/attributes", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAttributesResponse) {
			return http.StatusInternalServerError, clients.GetBusinessTermAttributesResponse{}
		},
	))

	mux.Handle("GET /rest/2.0/assets/{id}", testutil.JsonHandlerOut(
		func(r *http.Request) (int, clients.GetBusinessTermAssetResponse) {
			return http.StatusInternalServerError, clients.GetBusinessTermAssetResponse{}
		},
	))

	server := httptest.NewServer(mux)
	defer server.Close()

	client := testutil.NewClient(server)
	_, err := get_business_term.NewTool(client).Handler(t.Context(), get_business_term.Input{
		AssetID: "bt-err",
	})
	if err == nil {
		t.Fatal("expected error for server error, got nil")
	}
}
